[2016-06-03 17:16:07] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-03 17:16:07] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-03 17:16:07] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Namespace declaration statement has to be the very first statement in the script" at F:\xampp\htdocs\blog\src\BlogBundle\Controller\DefaultController.php line 3 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Namespace declaration statement has to be the very first statement in the script at F:\\xampp\\htdocs\\blog\\src\\BlogBundle\\Controller\\DefaultController.php:3)"} []
[2016-06-03 17:16:17] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-03 17:16:17] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-03 17:16:17] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Namespace declaration statement has to be the very first statement in the script" at F:\xampp\htdocs\blog\src\BlogBundle\Controller\DefaultController.php line 3 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Namespace declaration statement has to be the very first statement in the script at F:\\xampp\\htdocs\\blog\\src\\BlogBundle\\Controller\\DefaultController.php:3)"} []
[2016-06-04 16:15:07] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-04 16:15:08] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-04 16:15:08] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Parse Error: syntax error, unexpected ':'" at F:\xampp\htdocs\blog\src\BlogBundle\Controller\DefaultController.php line 18 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Parse Error: syntax error, unexpected ':' at F:\\xampp\\htdocs\\blog\\src\\BlogBundle\\Controller\\DefaultController.php:18)"} []
[2016-06-05 15:37:47] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-05 15:37:47] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-05 15:37:47] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class DateTime could not be converted to string") in "BlogBundle:Default:posts.html.twig" at line 8." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 1275 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Object of class DateTime could not be converted to string\") in \"BlogBundle:Default:posts.html.twig\" at line 8. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:1275, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class DateTime could not be converted to string at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\twig\\ec\\ec61e51cdca655e3db1486d1aacc48f6194982dca1811e251969cbb646991cf8.php:35)"} []
[2016-06-05 15:39:03] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-05 15:39:03] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-05 15:39:05] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class DateTime could not be converted to string") in "BlogBundle:Default:posts.html.twig" at line 8." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 1275 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Object of class DateTime could not be converted to string\") in \"BlogBundle:Default:posts.html.twig\" at line 8. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:1275, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class DateTime could not be converted to string at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\twig\\ec\\ec61e51cdca655e3db1486d1aacc48f6194982dca1811e251969cbb646991cf8.php:35)"} []
[2016-06-05 18:54:15] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-05 18:54:15] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-05 18:54:16] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class DateTime could not be converted to string") in "BlogBundle:Default:posts.html.twig" at line 8." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 1275 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Object of class DateTime could not be converted to string\") in \"BlogBundle:Default:posts.html.twig\" at line 8. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:1275, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class DateTime could not be converted to string at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\twig\\ec\\ec61e51cdca655e3db1486d1aacc48f6194982dca1811e251969cbb646991cf8.php:35)"} []
[2016-06-05 18:54:28] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-05 18:54:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-05 18:54:28] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class DateTime could not be converted to string") in "BlogBundle:Default:posts.html.twig" at line 8." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 1275 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Object of class DateTime could not be converted to string\") in \"BlogBundle:Default:posts.html.twig\" at line 8. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:1275, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class DateTime could not be converted to string at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\twig\\ec\\ec61e51cdca655e3db1486d1aacc48f6194982dca1811e251969cbb646991cf8.php:35)"} []
[2016-06-05 18:54:38] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-05 18:54:38] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-05 18:54:38] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class DateTime could not be converted to string") in "BlogBundle:Default:posts.html.twig" at line 8." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 1275 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Object of class DateTime could not be converted to string\") in \"BlogBundle:Default:posts.html.twig\" at line 8. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:1275, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class DateTime could not be converted to string at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\twig\\ec\\ec61e51cdca655e3db1486d1aacc48f6194982dca1811e251969cbb646991cf8.php:35)"} []
[2016-06-05 18:54:51] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-05 18:54:51] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-05 18:54:51] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class DateTime could not be converted to string") in "BlogBundle:Default:posts.html.twig" at line 8." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 1275 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Object of class DateTime could not be converted to string\") in \"BlogBundle:Default:posts.html.twig\" at line 8. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:1275, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class DateTime could not be converted to string at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\twig\\ec\\ec61e51cdca655e3db1486d1aacc48f6194982dca1811e251969cbb646991cf8.php:35)"} []
[2016-06-05 18:55:13] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-05 18:55:13] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-05 18:55:14] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class DateTime could not be converted to string") in "BlogBundle:Default:posts.html.twig" at line 8." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 1275 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Object of class DateTime could not be converted to string\") in \"BlogBundle:Default:posts.html.twig\" at line 8. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:1275, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class DateTime could not be converted to string at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\twig\\ec\\ec61e51cdca655e3db1486d1aacc48f6194982dca1811e251969cbb646991cf8.php:35)"} []
[2016-06-05 20:31:49] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-05 20:31:49] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-05 20:31:49] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 3 passed to Symfony\Bundle\FrameworkBundle\Controller\Controller::render() must be an instance of Symfony\Component\HttpFoundation\Response, array given, called in F:\xampp\htdocs\blog\src\BlogBundle\Controller\DefaultController.php on line 15 and defined" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 182 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 3 passed to Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller::render() must be an instance of Symfony\\Component\\HttpFoundation\\Response, array given, called in F:\\xampp\\htdocs\\blog\\src\\BlogBundle\\Controller\\DefaultController.php on line 15 and defined at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:182)"} []
[2016-06-06 19:18:44] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-06 19:18:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-06 19:18:51] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class DateTime could not be converted to string") in "BlogBundle:Default:posts.html.twig" at line 8." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 1275 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Object of class DateTime could not be converted to string\") in \"BlogBundle:Default:posts.html.twig\" at line 8. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:1275, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class DateTime could not be converted to string at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\twig\\ec\\ec61e51cdca655e3db1486d1aacc48f6194982dca1811e251969cbb646991cf8.php:35)"} []
[2016-06-07 10:04:09] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-07 10:04:09] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-07 10:04:10] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class DateTime could not be converted to string") in "BlogBundle:Default:posts.html.twig" at line 8." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 1275 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Object of class DateTime could not be converted to string\") in \"BlogBundle:Default:posts.html.twig\" at line 8. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:1275, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class DateTime could not be converted to string at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\twig\\ec\\ec61e51cdca655e3db1486d1aacc48f6194982dca1811e251969cbb646991cf8.php:35)"} []
[2016-06-07 17:08:27] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-07 17:08:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-07 17:08:33] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class DateTime could not be converted to string") in "BlogBundle:Default:posts.html.twig" at line 8." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 1275 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Object of class DateTime could not be converted to string\") in \"BlogBundle:Default:posts.html.twig\" at line 8. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:1275, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class DateTime could not be converted to string at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\twig\\ec\\ec61e51cdca655e3db1486d1aacc48f6194982dca1811e251969cbb646991cf8.php:35)"} []
[2016-06-08 13:08:57] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /app/login"" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /app/login\" at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:57)"} []
[2016-06-08 14:03:40] request.INFO: Matched route "blog_homepage". {"route_parameters":{"_controller":"BlogBundle\\Controller\\DefaultController::indexAction","_route":"blog_homepage"},"request_uri":"http://localhost/blog/web/"} []
[2016-06-08 14:03:40] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-08 14:03:40] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class DateTime could not be converted to string") in "BlogBundle:Default:posts.html.twig" at line 8." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 1275 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Object of class DateTime could not be converted to string\") in \"BlogBundle:Default:posts.html.twig\" at line 8. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:1275, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class DateTime could not be converted to string at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\twig\\ec\\ec61e51cdca655e3db1486d1aacc48f6194982dca1811e251969cbb646991cf8.php:35)"} []
[2016-06-08 14:04:48] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 14:08:58] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 14:10:48] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 14:10:56] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 14:11:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 14:20:41] request.INFO: Matched route "blog_admin". {"route_parameters":{"_controller":"BlogBundle:Admin:index","_route":"blog_admin"},"request_uri":"http://localhost/blog/web/admin/"} []
[2016-06-08 14:20:41] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The _controller value "BlogBundle:Admin:index" maps to a "BlogBundle\Controller\AdminController" class, but this class was not found. Create this class or check the spelling of the class and its namespace." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 819 {"exception":"[object] (InvalidArgumentException(code: 0): The _controller value \"BlogBundle:Admin:index\" maps to a \"BlogBundle\\Controller\\AdminController\" class, but this class was not found. Create this class or check the spelling of the class and its namespace. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:819)"} []
[2016-06-08 14:21:35] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 14:21:51] request.INFO: Matched route "blog_admin". {"route_parameters":{"_controller":"BlogBundle:Admin:index","_route":"blog_admin"},"request_uri":"http://localhost/blog/web/admin/"} []
[2016-06-08 14:21:51] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2016-06-08 14:21:51] security.DEBUG: User was reloaded from a user provider. {"username":"Mark","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-06-08 14:21:51] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The _controller value "BlogBundle:Admin:index" maps to a "BlogBundle\Controller\AdminController" class, but this class was not found. Create this class or check the spelling of the class and its namespace." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 819 {"exception":"[object] (InvalidArgumentException(code: 0): The _controller value \"BlogBundle:Admin:index\" maps to a \"BlogBundle\\Controller\\AdminController\" class, but this class was not found. Create this class or check the spelling of the class and its namespace. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:819)"} []
[2016-06-08 14:21:51] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2016-06-08 14:47:42] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 14:56:52] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 14:56:54] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 14:58:20] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 14:58:22] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 14:59:12] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 14:59:23] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/app_dev.php")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/app_dev.php\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 14:59:52] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/app_dev.php")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/app_dev.php\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 15:00:16] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/app_dev.php")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/app_dev.php\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 15:00:18] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/app_dev.php")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/app_dev.php\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 15:00:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/app_dev.php")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/app_dev.php\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 15:02:24] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/app_dev.php")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/app_dev.php\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 15:02:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/app_dev.php")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/app_dev.php\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 15:03:04] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login" (from "http://localhost/blog/web/app_dev.php")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" (from \"http://localhost/blog/web/app_dev.php\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:74)"} []
[2016-06-08 15:06:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /login/login" (from "http://localhost/blog/web/login/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /login/login\" (from \"http://localhost/blog/web/login/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:83)"} []
[2016-06-08 15:07:18] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /login/login" (from "http://localhost/blog/web/login/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /login/login\" (from \"http://localhost/blog/web/login/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:83)"} []
[2016-06-08 15:07:30] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /login/login" (from "http://localhost/blog/web/login/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /login/login\" (from \"http://localhost/blog/web/login/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:83)"} []
[2016-06-08 15:07:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /login/login" (from "http://localhost/blog/web/login/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /login/login\" (from \"http://localhost/blog/web/login/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:83)"} []
[2016-06-08 15:13:26] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /login/login" (from "http://localhost/blog/web/login/")" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /login/login\" (from \"http://localhost/blog/web/login/\") at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:83)"} []
[2016-06-08 17:08:45] request.INFO: Matched route "blog_admin". {"route_parameters":{"_controller":"BlogBundle:Admin:index","_route":"blog_admin"},"request_uri":"http://localhost/blog/web/admin/"} []
[2016-06-08 17:08:45] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The _controller value "BlogBundle:Admin:index" maps to a "BlogBundle\Controller\AdminController" class, but this class was not found. Create this class or check the spelling of the class and its namespace." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 819 {"exception":"[object] (InvalidArgumentException(code: 0): The _controller value \"BlogBundle:Admin:index\" maps to a \"BlogBundle\\Controller\\AdminController\" class, but this class was not found. Create this class or check the spelling of the class and its namespace. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:819)"} []
[2016-06-08 17:09:32] request.INFO: Matched route "blog_admin". {"route_parameters":{"_controller":"BlogBundle:Admin:index","_route":"blog_admin"},"request_uri":"http://localhost/blog/web/admin/"} []
[2016-06-08 17:09:32] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The _controller value "BlogBundle:Admin:index" maps to a "BlogBundle\Controller\AdminController" class, but this class was not found. Create this class or check the spelling of the class and its namespace." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 819 {"exception":"[object] (InvalidArgumentException(code: 0): The _controller value \"BlogBundle:Admin:index\" maps to a \"BlogBundle\\Controller\\AdminController\" class, but this class was not found. Create this class or check the spelling of the class and its namespace. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:819)"} []
[2016-06-08 17:10:30] request.INFO: Matched route "blog_admin". {"route_parameters":{"_controller":"BlogBundle:Admin:index","_route":"blog_admin"},"request_uri":"http://localhost/blog/web/admin/"} []
[2016-06-08 17:10:30] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The _controller value "BlogBundle:Admin:index" maps to a "BlogBundle\Controller\AdminController" class, but this class was not found. Create this class or check the spelling of the class and its namespace." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 819 {"exception":"[object] (InvalidArgumentException(code: 0): The _controller value \"BlogBundle:Admin:index\" maps to a \"BlogBundle\\Controller\\AdminController\" class, but this class was not found. Create this class or check the spelling of the class and its namespace. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:819)"} []
[2016-06-08 17:10:45] request.INFO: Matched route "blog_admin". {"route_parameters":{"_controller":"BlogBundle:Admin:index","_route":"blog_admin"},"request_uri":"http://localhost/blog/web/admin/"} []
[2016-06-08 17:10:45] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The _controller value "BlogBundle:Admin:index" maps to a "BlogBundle\Controller\AdminController" class, but this class was not found. Create this class or check the spelling of the class and its namespace." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 819 {"exception":"[object] (InvalidArgumentException(code: 0): The _controller value \"BlogBundle:Admin:index\" maps to a \"BlogBundle\\Controller\\AdminController\" class, but this class was not found. Create this class or check the spelling of the class and its namespace. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:819)"} []
[2016-06-08 17:11:44] request.INFO: Matched route "blog_admin". {"route_parameters":{"_controller":"BlogBundle:Admin:index","_route":"blog_admin"},"request_uri":"http://localhost/blog/web/admin/"} []
[2016-06-08 17:11:44] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The _controller value "BlogBundle:Admin:index" maps to a "BlogBundle\Controller\AdminController" class, but this class was not found. Create this class or check the spelling of the class and its namespace." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 819 {"exception":"[object] (InvalidArgumentException(code: 0): The _controller value \"BlogBundle:Admin:index\" maps to a \"BlogBundle\\Controller\\AdminController\" class, but this class was not found. Create this class or check the spelling of the class and its namespace. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:819)"} []
[2016-06-08 23:15:03] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "POST /login": Method Not Allowed (Allow: GET, HEAD)" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 180 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"POST /login\": Method Not Allowed (Allow: GET, HEAD) at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:180, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:73)"} []
[2016-06-08 23:16:41] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "POST /login": Method Not Allowed (Allow: GET, HEAD)" at F:\xampp\htdocs\blog\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 180 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"POST /login\": Method Not Allowed (Allow: GET, HEAD) at F:\\xampp\\htdocs\\blog\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:180, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlMatcher.php:73)"} []
[2016-06-09 13:19:30] request.INFO: Matched route "login". {"route_parameters":{"_controller":"BlogBundle\\Controller\\SecurityController::loginAction","_route":"login"},"request_uri":"http://localhost/blog/web/login"} []
[2016-06-09 13:19:30] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "/login_check" as such route does not exist.") in "BlogBundle:Default:login.html.twig" at line 23." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 1190 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"/login_check\" as such route does not exist.\") in \"BlogBundle:Default:login.html.twig\" at line 23. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:1190, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"/login_check\" as such route does not exist. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlGenerator.php:37)"} []
[2016-06-09 13:19:35] request.INFO: Matched route "login". {"route_parameters":{"_controller":"BlogBundle\\Controller\\SecurityController::loginAction","_route":"login"},"request_uri":"http://localhost/blog/web/login"} []
[2016-06-09 13:19:35] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "/login_check" as such route does not exist.") in "BlogBundle:Default:login.html.twig" at line 23." at F:\xampp\htdocs\blog\app\cache\prod\classes.php line 1190 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"/login_check\" as such route does not exist.\") in \"BlogBundle:Default:login.html.twig\" at line 23. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\classes.php:1190, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"/login_check\" as such route does not exist. at F:\\xampp\\htdocs\\blog\\app\\cache\\prod\\appProdUrlGenerator.php:37)"} []
[2016-06-09 13:49:05] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/blog/web/login_check"} []
[2016-06-09 13:49:05] request.WARNING: Unable to look for the controller as the "_controller" parameter is missing. [] []
[2016-06-09 13:49:05] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Unable to find the controller for path "/login_check". The route is wrongly configured." at F:\xampp\htdocs\blog\app\bootstrap.php.cache line 3200 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Unable to find the controller for path \"/login_check\". The route is wrongly configured. at F:\\xampp\\htdocs\\blog\\app\\bootstrap.php.cache:3200)"} []
[2016-06-09 13:49:17] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/blog/web/login_check"} []
[2016-06-09 13:49:17] request.WARNING: Unable to look for the controller as the "_controller" parameter is missing. [] []
[2016-06-09 13:49:17] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Unable to find the controller for path "/login_check". The route is wrongly configured." at F:\xampp\htdocs\blog\app\bootstrap.php.cache line 3200 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Unable to find the controller for path \"/login_check\". The route is wrongly configured. at F:\\xampp\\htdocs\\blog\\app\\bootstrap.php.cache:3200)"} []
[2016-06-10 12:39:07] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/blog/web/login_check"} []
[2016-06-10 12:39:07] request.WARNING: Unable to look for the controller as the "_controller" parameter is missing. [] []
[2016-06-10 12:39:07] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Unable to find the controller for path "/login_check". The route is wrongly configured." at F:\xampp\htdocs\blog\app\bootstrap.php.cache line 3200 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Unable to find the controller for path \"/login_check\". The route is wrongly configured. at F:\\xampp\\htdocs\\blog\\app\\bootstrap.php.cache:3200)"} []
[2016-06-10 12:39:30] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/blog/web/login_check"} []
[2016-06-10 12:39:30] request.WARNING: Unable to look for the controller as the "_controller" parameter is missing. [] []
[2016-06-10 12:39:30] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Unable to find the controller for path "/login_check". The route is wrongly configured." at F:\xampp\htdocs\blog\app\bootstrap.php.cache line 3200 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Unable to find the controller for path \"/login_check\". The route is wrongly configured. at F:\\xampp\\htdocs\\blog\\app\\bootstrap.php.cache:3200)"} []
[2016-06-10 14:24:38] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/blog/web/login_check"} []
[2016-06-10 14:24:38] request.WARNING: Unable to look for the controller as the "_controller" parameter is missing. [] []
[2016-06-10 14:24:38] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Unable to find the controller for path "/login_check". The route is wrongly configured." at F:\xampp\htdocs\blog\app\bootstrap.php.cache line 3200 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Unable to find the controller for path \"/login_check\". The route is wrongly configured. at F:\\xampp\\htdocs\\blog\\app\\bootstrap.php.cache:3200)"} []
[2016-06-10 14:24:51] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/blog/web/login_check"} []
[2016-06-10 14:24:51] request.WARNING: Unable to look for the controller as the "_controller" parameter is missing. [] []
[2016-06-10 14:24:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Unable to find the controller for path "/login_check". The route is wrongly configured." at F:\xampp\htdocs\blog\app\bootstrap.php.cache line 3200 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Unable to find the controller for path \"/login_check\". The route is wrongly configured. at F:\\xampp\\htdocs\\blog\\app\\bootstrap.php.cache:3200)"} []
